### ISSUE TITLE
Video repeating on .zschrc replacement

### ISSUE THREAD

**Issue by halesyy** [danshea00/.dotfiles#1]
When I replaced your `.zschrc` in my own, my computer restarted, and now there is a video of a mime doing falic things on my screen repeatedly, saying "suck it, jack hales" ?????

https://www.youtube.com/watch?v=DIgqx5cUyXM

**Comment by danshea00** [comment]
This is expected behaviour

**Comment by halesyy** [comment]
Thanks for marking as completed, very happy with this repo - giving it a star ⭐️
